In [399]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy.special as special
from scipy.optimize import curve_fit
import seaborn as sns
from sklearn.metrics import r2_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from imblearn.over_sampling import SMOTE


In [400]:
df = pd.read_csv("Wuppi convertido.csv")
df.head()

Unnamed: 0.1  Unnamed: 0  Administrador  Usuario  botón correcto  \
0             0           0            2.0      3.0             1.0   
1             1           1            2.0      3.0             0.0   
2             2           2            2.0      3.0             1.0   
3             3           3            2.0      3.0             0.0   
4             4           4            2.0      3.0             0.0   

   tiempo de interacción  mini juego  número de interacción  color presionado  \
0               5.399169         9.0                    1.0               4.0   
1               1.283400         9.0                    2.0               1.0   
2               2.700226         9.0                    3.0               2.0   
3               3.050262         9.0                    4.0               2.0   
4               4.750256         9.0                    5.0               2.0   

   dificultad                      fecha  Juego  auto push  tiempo de lección  \
0         1.0  25/01/2024 09:26:42 a. m.    1.0        0.0                0.0   
1         1.0  25/01/2024 09:26:46 a. m.    1.0        0.0                0.0   
2         1.0  25/01/2024 09:26:48 a. m.    1.0        0.0                0.0   
3         1.0  25/01/2024 09:26:57 a. m.    1.0        0.0                0.0   
4         1.0  25/01/2024 09:26:58 a. m.    1.0        0.0                0.0   

   tiempo de sesión  
0               0.0  
1               0.0  
2               0.0  
3               0.0  
4               0.0

In [401]:
df = df.drop(columns=["Unnamed: 0.1","Unnamed: 0","fecha"])

In [402]:
df_no_numerico = df.copy()

In [403]:
df_no_numerico2 = df.copy()

In [404]:
df_no_numerico3 = df.copy()

In [526]:
df_no_numerico4 = df.copy()

# Auto Push

## Sin balanceo

In [405]:
df_no_numerico["auto push"]= df_no_numerico["auto push"].replace([1], "correcto")
df_no_numerico["auto push"]= df_no_numerico["auto push"].replace([0], "incorrecto")

In [406]:
Var_Indep = df[["color presionado", "Usuario", "tiempo de interacción"]]
Var_Dep= df_no_numerico["auto push"]
X = Var_Indep
y = Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.25, random_state=None)
escala= StandardScaler()
X_train = escala.fit_transform(X_train)
X_test = escala.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [407]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['incorrecto', 'incorrecto', 'incorrecto', ..., 'incorrecto',
       'incorrecto', 'incorrecto'], shape=(1467,), dtype=object)

In [408]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="correcto")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="correcto")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[   0   14]
 [   1 1452]]
Precision del modelo
0.0
Exactitud del modelo
0.9897750511247444
la sensibilidad del modelo es
0.0


## Reponderación de clase

In [409]:
algoritmo_pond = LogisticRegression(class_weight="balanced")
algoritmo_pond.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [410]:
y_pred_pond = algoritmo_pond.predict(X_test)
y_pred_pond

array(['incorrecto', 'incorrecto', 'incorrecto', ..., 'incorrecto',
       'incorrecto', 'incorrecto'], shape=(1467,), dtype=object)

In [411]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_pond)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[  14    0]
 [ 103 1350]]


In [412]:

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="correcto")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="correcto")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.11965811965811966
Exactitud del modelo
0.9297886843899114
la sensibilidad del modelo es
1.0


In [413]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="incorrecto")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="incorrecto")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
1.0
Exactitud del modelo
0.9297886843899114
la sensibilidad del modelo es
0.9291121816930489


## Submuestreo

In [414]:
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

In [415]:
algoritmo_over_sampling = LogisticRegression()
algoritmo_over_sampling.fit(X_resampled, y_resampled)

LogisticRegression()

In [416]:
y_pred_over_sampling = algoritmo_over_sampling.predict(X_test)
y_pred_over_sampling

array(['incorrecto', 'incorrecto', 'incorrecto', ..., 'incorrecto',
       'incorrecto', 'incorrecto'], shape=(1467,), dtype=object)

In [417]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_over_sampling)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[  14    0]
 [  99 1354]]


In [418]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="correcto")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="correcto")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.12389380530973451
Exactitud del modelo
0.9325153374233128
la sensibilidad del modelo es
1.0


In [419]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="incorrecto")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="incorrecto")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
1.0
Exactitud del modelo
0.9325153374233128
la sensibilidad del modelo es
0.9318651066758431


# Azul, Verde, Amarillo

## Azul

### Sin balanceo

In [420]:
df_no_numerico["color presionado"]= df_no_numerico["color presionado"].replace([4], "azul")
df_no_numerico["color presionado"]= df_no_numerico["color presionado"].replace([1,2,3,5,99], "otros colores")

In [421]:
Var_Indep = df[["tiempo de interacción", "número de interacción", "tiempo de lección"]]
Var_Dep= df_no_numerico["color presionado"]
X = Var_Indep
y = Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)
escala= StandardScaler()
X_train = escala.fit_transform(X_train)
X_test = escala.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [422]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['otros colores', 'otros colores', 'otros colores', ...,
       'otros colores', 'otros colores', 'otros colores'],
      shape=(1760,), dtype=object)

In [423]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="azul")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="azul")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[   0  346]
 [   0 1414]]
Precision del modelo
0.0
Exactitud del modelo
0.803409090909091
la sensibilidad del modelo es
0.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [424]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="otros colores")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="otros colores")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[   0  346]
 [   0 1414]]
Precision del modelo
0.803409090909091
Exactitud del modelo
0.803409090909091
la sensibilidad del modelo es
1.0


### Reponderación de clases

In [425]:
algoritmo_pond = LogisticRegression(class_weight="balanced")
algoritmo_pond.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [426]:
y_pred_pond = algoritmo_pond.predict(X_test)
y_pred_pond

array(['azul', 'azul', 'otros colores', ..., 'azul', 'azul', 'azul'],
      shape=(1760,), dtype=object)

In [427]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_pond)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[ 300   46]
 [1010  404]]


In [428]:

from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="azul")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="azul")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.22900763358778625
Exactitud del modelo
0.4
la sensibilidad del modelo es
0.8670520231213873


In [429]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="otros colores")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="otros colores")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.8977777777777778
Exactitud del modelo
0.4
la sensibilidad del modelo es
0.2857142857142857


### Submuestreo

In [430]:
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

In [431]:
algoritmo_over_sampling = LogisticRegression()
algoritmo_over_sampling.fit(X_resampled, y_resampled)

LogisticRegression()

In [432]:
y_pred_over_sampling = algoritmo_over_sampling.predict(X_test)
y_pred_over_sampling

array(['azul', 'azul', 'otros colores', ..., 'azul', 'azul', 'azul'],
      shape=(1760,), dtype=object)

In [433]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_over_sampling)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[ 298   48]
 [1007  407]]


In [434]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="azul")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="azul")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.22835249042145594
Exactitud del modelo
0.4005681818181818
la sensibilidad del modelo es
0.861271676300578


## Amarillo

### Sin balanceo

In [435]:
df_no_numerico2["color presionado"]= df_no_numerico2["color presionado"].replace([3], "amarillo")
df_no_numerico2["color presionado"]= df_no_numerico2["color presionado"].replace([1,2,4,5,99], "otros colores")

In [436]:
Var_Indep = df[["tiempo de interacción", "número de interacción", "tiempo de lección"]]
Var_Dep= df_no_numerico2["color presionado"]
X = Var_Indep
y = Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)
escala= StandardScaler()
X_train = escala.fit_transform(X_train)
X_test = escala.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [437]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['otros colores', 'otros colores', 'otros colores', ...,
       'otros colores', 'otros colores', 'otros colores'],
      shape=(1760,), dtype=object)

In [438]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="amarillo")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="amarillo")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[   0  366]
 [   0 1394]]
Precision del modelo
0.0
Exactitud del modelo
0.7920454545454545
la sensibilidad del modelo es
0.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [439]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="otros colores")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="otros colores")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[   0  366]
 [   0 1394]]
Precision del modelo
0.7920454545454545
Exactitud del modelo
0.7920454545454545
la sensibilidad del modelo es
1.0


### Reponderación de clases

In [440]:
algoritmo_pond = LogisticRegression(class_weight="balanced")
algoritmo_pond.fit(X_train, y_train)
y_pred_pond = algoritmo_pond.predict(X_test)
y_pred_pond

array(['amarillo', 'amarillo', 'amarillo', ..., 'amarillo', 'amarillo',
       'otros colores'], shape=(1760,), dtype=object)

In [441]:
matriz = confusion_matrix(y_test, y_pred_pond)
print("Matriz de confusión")
print(matriz)


Matriz de confusión
[[309  57]
 [922 472]]


In [442]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="amarillo")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="amarillo")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.2510154346060114
Exactitud del modelo
0.44375
la sensibilidad del modelo es
0.8442622950819673


In [443]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="otros colores")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="otros colores")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.8922495274102079
Exactitud del modelo
0.44375
la sensibilidad del modelo es
0.3385939741750359


### Submuestreo

In [444]:
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)
algoritmo_over_sampling = LogisticRegression()
algoritmo_over_sampling.fit(X_resampled, y_resampled)
y_pred_over_sampling = algoritmo_over_sampling.predict(X_test)
y_pred_over_sampling

array(['amarillo', 'amarillo', 'amarillo', ..., 'amarillo', 'amarillo',
       'otros colores'], shape=(1760,), dtype=object)

In [445]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_over_sampling)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="amarillo")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="amarillo")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[304  62]
 [917 477]]
Precision del modelo
0.24897624897624898
Exactitud del modelo
0.44375
la sensibilidad del modelo es
0.8306010928961749


In [446]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_over_sampling)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros colores")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros colores")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[304  62]
 [917 477]]
Precision del modelo
0.8849721706864564
Exactitud del modelo
0.44375
la sensibilidad del modelo es
0.34218077474892394


## Verde

In [447]:
df_no_numerico3["color presionado"]= df_no_numerico3["color presionado"].replace([2], "verde")
df_no_numerico3["color presionado"]= df_no_numerico3["color presionado"].replace([1,3,4,5,99], "otros colores")

In [448]:
Var_Indep = df[["tiempo de interacción", "número de interacción", "tiempo de lección"]]
Var_Dep= df_no_numerico3["color presionado"]
X = Var_Indep
y = Var_Dep

In [449]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)
escala= StandardScaler()
X_train = escala.fit_transform(X_train)
X_test = escala.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [450]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['otros colores', 'otros colores', 'otros colores', ...,
       'otros colores', 'otros colores', 'otros colores'],
      shape=(1760,), dtype=object)

In [451]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="verde")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="verde")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[1368    0]
 [ 392    0]]
Precision del modelo
0.0
Exactitud del modelo
0.7772727272727272
la sensibilidad del modelo es
0.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [452]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="otros colores")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="otros colores")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[1368    0]
 [ 392    0]]
Precision del modelo
0.7772727272727272
Exactitud del modelo
0.7772727272727272
la sensibilidad del modelo es
1.0


### Reponderación de clases

In [453]:
algoritmo_pond = LogisticRegression(class_weight="balanced")
algoritmo_pond.fit(X_train, y_train)
y_pred_pond = algoritmo_pond.predict(X_test)
y_pred_pond

array(['verde', 'otros colores', 'otros colores', ..., 'verde',
       'otros colores', 'verde'], shape=(1760,), dtype=object)

In [454]:
matriz = confusion_matrix(y_test, y_pred_pond)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[412 956]
 [ 40 352]]


In [455]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="verde")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="verde")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.2691131498470948
Exactitud del modelo
0.4340909090909091
la sensibilidad del modelo es
0.8979591836734694


In [456]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="otros colores")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="otros colores")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.911504424778761
Exactitud del modelo
0.4340909090909091
la sensibilidad del modelo es
0.30116959064327486


### Submuestreo

In [457]:
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)
algoritmo_over_sampling = LogisticRegression()
algoritmo_over_sampling.fit(X_resampled, y_resampled)
y_pred_over_sampling = algoritmo_over_sampling.predict(X_test)
y_pred_over_sampling

array(['verde', 'otros colores', 'otros colores', ..., 'verde',
       'otros colores', 'verde'], shape=(1760,), dtype=object)

In [458]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_over_sampling)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[413 955]
 [ 43 349]]


In [459]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="verde")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="verde")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.26763803680981596
Exactitud del modelo
0.4329545454545455
la sensibilidad del modelo es
0.8903061224489796


In [460]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros colores")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros colores")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.9057017543859649
Exactitud del modelo
0.4329545454545455
la sensibilidad del modelo es
0.3019005847953216


# Mini Juego

## Asteroides

### Sin balancear

In [461]:
df_no_numerico["mini juego"]= df_no_numerico["mini juego"].replace([1], "Asteroides")
df_no_numerico["mini juego"]= df_no_numerico["mini juego"].replace([2,3,4,5,6,7,8,9,10,11,12,13,99], "otros mini juegos")

In [462]:
Var_Indep = df[["tiempo de sesión", "botón correcto", "color presionado"]]
Var_Dep= df_no_numerico["mini juego"]
X = Var_Indep
y = Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)
escala= StandardScaler()
X_train = escala.fit_transform(X_train)
X_test = escala.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [463]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['otros mini juegos', 'otros mini juegos', 'otros mini juegos', ...,
       'otros mini juegos', 'otros mini juegos', 'otros mini juegos'],
      shape=(1760,), dtype=object)

In [464]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Asteroides")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Asteroides")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[   0  323]
 [   0 1437]]
Precision del modelo
0.0
Exactitud del modelo
0.8164772727272728
la sensibilidad del modelo es
0.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [465]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="otros mini juegos")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="otros mini juegos")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[   0  323]
 [   0 1437]]
Precision del modelo
0.8164772727272728
Exactitud del modelo
0.8164772727272728
la sensibilidad del modelo es
1.0


### Reponderacion de clase

In [466]:
algoritmo_pond = LogisticRegression(class_weight="balanced")
algoritmo_pond.fit(X_train, y_train)
y_pred_pond = algoritmo_pond.predict(X_test)
y_pred_pond

array(['Asteroides', 'Asteroides', 'otros mini juegos', ..., 'Asteroides',
       'Asteroides', 'Asteroides'], shape=(1760,), dtype=object)

In [467]:
matriz = confusion_matrix(y_test, y_pred_pond)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[ 297   26]
 [1229  208]]


In [468]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="Asteroides")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="Asteroides")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.1946264744429882
Exactitud del modelo
0.2869318181818182
la sensibilidad del modelo es
0.9195046439628483


In [469]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="otros mini juegos")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="otros mini juegos")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.8888888888888888
Exactitud del modelo
0.2869318181818182
la sensibilidad del modelo es
0.14474599860821155


### Submuestreo

In [470]:
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)
algoritmo_over_sampling = LogisticRegression()
algoritmo_over_sampling.fit(X_resampled, y_resampled)
y_pred_over_sampling = algoritmo_over_sampling.predict(X_test)
y_pred_over_sampling

array(['Asteroides', 'Asteroides', 'otros mini juegos', ..., 'Asteroides',
       'Asteroides', 'Asteroides'], shape=(1760,), dtype=object)

In [471]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_over_sampling)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[ 297   26]
 [1229  208]]


In [472]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="Asteroides")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="Asteroides")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.1946264744429882
Exactitud del modelo
0.2869318181818182
la sensibilidad del modelo es
0.9195046439628483


In [473]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_over_sampling)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros mini juegos")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros mini juegos")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[ 297   26]
 [1229  208]]
Precision del modelo
0.8888888888888888
Exactitud del modelo
0.2869318181818182
la sensibilidad del modelo es
0.14474599860821155


## Restaurante

### Sin balancear

In [474]:
df_no_numerico2["mini juego"]= df_no_numerico2["mini juego"].replace([2], "restaurantes")
df_no_numerico2["mini juego"]= df_no_numerico2["mini juego"].replace([1,3,4,5,6,7,8,9,10,11,12,13,99], "otros mini juegos")

In [475]:
Var_Indep = df[["tiempo de sesión", "botón correcto", "color presionado"]]
Var_Dep= df_no_numerico2["mini juego"]
X = Var_Indep
y = Var_Dep

In [476]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)
escala= StandardScaler()
X_train = escala.fit_transform(X_train)
X_test = escala.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred = algoritmo.predict(X_test)
y_pred

array(['otros mini juegos', 'otros mini juegos', 'otros mini juegos', ...,
       'otros mini juegos', 'otros mini juegos', 'otros mini juegos'],
      shape=(1760,), dtype=object)

In [477]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[1495    0]
 [ 265    0]]


In [478]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="restaurantes")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="restaurantes")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.0
Exactitud del modelo
0.8494318181818182
la sensibilidad del modelo es
0.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [480]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="otros mini juegos")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="otros mini juegos")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.8494318181818182
Exactitud del modelo
0.8494318181818182
la sensibilidad del modelo es
1.0


### Reponderacion de clase

In [484]:
algoritmo_pond = LogisticRegression(class_weight="balanced")
algoritmo_pond.fit(X_train, y_train)
y_pred_pond = algoritmo_pond.predict(X_test)
y_pred_pond

array(['restaurantes', 'restaurantes', 'restaurantes', ...,
       'restaurantes', 'restaurantes', 'restaurantes'],
      shape=(1760,), dtype=object)

In [485]:
matriz = confusion_matrix(y_test, y_pred_pond)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[ 391 1104]
 [  52  213]]


In [487]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="restaurantes")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="restaurantes")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.16173120728929385
Exactitud del modelo
0.3431818181818182
la sensibilidad del modelo es
0.8037735849056604


In [488]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="otros mini juegos")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="otros mini juegos")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.8826185101580135
Exactitud del modelo
0.3431818181818182
la sensibilidad del modelo es
0.26153846153846155


### Submuestreo

In [489]:
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)
algoritmo_over_sampling = LogisticRegression()
algoritmo_over_sampling.fit(X_resampled, y_resampled)
y_pred_over_sampling = algoritmo_over_sampling.predict(X_test)
y_pred_over_sampling

array(['restaurantes', 'restaurantes', 'restaurantes', ...,
       'restaurantes', 'restaurantes', 'restaurantes'],
      shape=(1760,), dtype=object)

In [490]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_over_sampling)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[ 391 1104]
 [  52  213]]


In [492]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="restaurantes")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="restaurantes")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.16173120728929385
Exactitud del modelo
0.3431818181818182
la sensibilidad del modelo es
0.8037735849056604


In [493]:

from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_over_sampling)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros mini juegos")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros mini juegos")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[ 391 1104]
 [  52  213]]
Precision del modelo
0.8826185101580135
Exactitud del modelo
0.3431818181818182
la sensibilidad del modelo es
0.26153846153846155


# Usuarios (Leonardo, Ma del Rosario, Rene, Nicolas)

## Leonardo

### Sin balanceo

In [494]:
df_no_numerico["Usuario"]= df_no_numerico["Usuario"].replace([1], "Leonardo")
df_no_numerico["Usuario"]= df_no_numerico["Usuario"].replace([3,18,14,17,11,9,8,13,16,22,12,10,20,15,26,28,32,6,27,19,5,29,21,25,31,23,7,2,4,24,30], "otros usuarios")

In [495]:
Var_Indep = df[["Administrador", "Juego", "auto push"]]
Var_Dep= df_no_numerico["Usuario"]
X = Var_Indep
y = Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)
escala= StandardScaler()
X_train = escala.fit_transform(X_train)
X_test = escala.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()
algoritmo.fit(X_train, y_train)

LogisticRegression()

In [496]:
y_pred = algoritmo.predict(X_test)
y_pred

array(['otros usuarios', 'otros usuarios', 'otros usuarios', ...,
       'otros usuarios', 'otros usuarios', 'otros usuarios'],
      shape=(1760,), dtype=object)

In [497]:
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Leonardo")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Leonardo")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[   0  263]
 [   0 1497]]
Precision del modelo
0.0
Exactitud del modelo
0.8505681818181818
la sensibilidad del modelo es
0.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [498]:
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[   0  263]
 [   0 1497]]
Precision del modelo
0.8505681818181818
Exactitud del modelo
0.8505681818181818
la sensibilidad del modelo es
1.0


### Reponderacion de clases

In [499]:
algoritmo_pond = LogisticRegression(class_weight="balanced")
algoritmo_pond.fit(X_train, y_train)

LogisticRegression(class_weight='balanced')

In [500]:
y_pred_pond = algoritmo_pond.predict(X_test)
y_pred_pond

array(['Leonardo', 'otros usuarios', 'Leonardo', ..., 'otros usuarios',
       'Leonardo', 'otros usuarios'], shape=(1760,), dtype=object)

In [501]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_pond)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[217  46]
 [582 915]]


In [502]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="Leonardo")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="Leonardo")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.2715894868585732
Exactitud del modelo
0.6431818181818182
la sensibilidad del modelo es
0.8250950570342205


In [503]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.9521331945889698
Exactitud del modelo
0.6431818181818182
la sensibilidad del modelo es
0.6112224448897795


### Submuestreo

In [504]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)

In [505]:
algoritmo_over_sampling = LogisticRegression()
algoritmo_over_sampling.fit(X_resampled, y_resampled)

LogisticRegression()

In [506]:
y_pred_over_sampling = algoritmo_over_sampling.predict(X_test)
y_pred_over_sampling

array(['Leonardo', 'otros usuarios', 'Leonardo', ..., 'otros usuarios',
       'Leonardo', 'otros usuarios'], shape=(1760,), dtype=object)

In [507]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="Leonardo")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="Leonardo")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.2715894868585732
Exactitud del modelo
0.6431818181818182
la sensibilidad del modelo es
0.8250950570342205


In [508]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.9521331945889698
Exactitud del modelo
0.6431818181818182
la sensibilidad del modelo es
0.6112224448897795


## MA del Rosario

### Sin balanceo

In [513]:
df_no_numerico2["Usuario"]= df_no_numerico2["Usuario"].replace([24], "Ma del Rosario")
df_no_numerico2["Usuario"]= df_no_numerico2["Usuario"].replace([3,18,14,17,11,9,8,13,16,22,12,10,20,15,26,28,32,6,27,19,5,29,21,25,31,23,7,2,4,1,30], "otros usuarios")

In [514]:
Var_Indep = df[["Administrador", "Juego", "auto push"]]
Var_Dep= df_no_numerico2["Usuario"]
X = Var_Indep
y = Var_Dep

In [515]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)
escala= StandardScaler()
X_train = escala.fit_transform(X_train)
X_test = escala.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred = algoritmo.predict(X_test)
y_pred

array(['otros usuarios', 'otros usuarios', 'otros usuarios', ...,
       'otros usuarios', 'otros usuarios', 'otros usuarios'],
      shape=(1760,), dtype=object)

In [516]:
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0   17]
 [   0 1743]]


In [517]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Ma del Rosario")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Ma del Rosario")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.0
Exactitud del modelo
0.9903409090909091
la sensibilidad del modelo es
0.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [518]:
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Matriz de confusión
[[   0   17]
 [   0 1743]]
Precision del modelo
0.9903409090909091
Exactitud del modelo
0.9903409090909091
la sensibilidad del modelo es
1.0


### Reponderacion de clases

In [519]:
algoritmo_pond = LogisticRegression(class_weight="balanced")
algoritmo_pond.fit(X_train, y_train)
y_pred_pond = algoritmo_pond.predict(X_test)
y_pred_pond

array(['Ma del Rosario', 'otros usuarios', 'Ma del Rosario', ...,
       'Ma del Rosario', 'Ma del Rosario', 'Ma del Rosario'],
      shape=(1760,), dtype=object)

In [520]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_pond)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[  17    0]
 [ 604 1139]]


In [521]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="Ma del Rosario")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="Ma del Rosario")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.027375201288244767
Exactitud del modelo
0.6568181818181819
la sensibilidad del modelo es
1.0


In [522]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
1.0
Exactitud del modelo
0.6568181818181819
la sensibilidad del modelo es
0.6534710269650029


### Submuestreo

In [523]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)
algoritmo_over_sampling = LogisticRegression()
algoritmo_over_sampling.fit(X_resampled, y_resampled)
y_pred_over_sampling = algoritmo_over_sampling.predict(X_test)
y_pred_over_sampling

array(['Ma del Rosario', 'otros usuarios', 'Ma del Rosario', ...,
       'Ma del Rosario', 'Ma del Rosario', 'Ma del Rosario'],
      shape=(1760,), dtype=object)

In [524]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="Ma del Rosario")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="Ma del Rosario")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.027375201288244767
Exactitud del modelo
0.6568181818181819
la sensibilidad del modelo es
1.0


In [525]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
1.0
Exactitud del modelo
0.6568181818181819
la sensibilidad del modelo es
0.6534710269650029


## Nicolas

### Sin balanceo

In [527]:
df_no_numerico3["Usuario"]= df_no_numerico3["Usuario"].replace([3], "Nicolas")
df_no_numerico3["Usuario"]= df_no_numerico3["Usuario"].replace([24,18,14,17,11,9,8,13,16,22,12,10,20,15,26,28,32,6,27,19,5,29,21,25,31,23,7,2,4,1,30], "otros usuarios")

In [529]:
Var_Indep = df[["Administrador", "Juego", "auto push"]]
Var_Dep= df_no_numerico3["Usuario"]
X = Var_Indep
y = Var_Dep
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)
escala= StandardScaler()
X_train = escala.fit_transform(X_train)
X_test = escala.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred = algoritmo.predict(X_test)
y_pred

array(['otros usuarios', 'otros usuarios', 'otros usuarios', ...,
       'otros usuarios', 'otros usuarios', 'otros usuarios'],
      shape=(1760,), dtype=object)

In [530]:
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0  174]
 [   0 1586]]


In [532]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Nicolas")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Nicolas")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.0
Exactitud del modelo
0.9011363636363636
la sensibilidad del modelo es
0.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [533]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.9011363636363636
Exactitud del modelo
0.9011363636363636
la sensibilidad del modelo es
1.0


### Reponderacion de clases

In [534]:
algoritmo_pond = LogisticRegression(class_weight="balanced")
algoritmo_pond.fit(X_train, y_train)
y_pred_pond = algoritmo_pond.predict(X_test)
y_pred_pond

array(['Nicolas', 'Nicolas', 'Nicolas', ..., 'otros usuarios', 'Nicolas',
       'Nicolas'], shape=(1760,), dtype=object)

In [535]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_pond)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[174   0]
 [910 676]]


In [536]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="Nicolas")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="Nicolas")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.16051660516605165
Exactitud del modelo
0.48295454545454547
la sensibilidad del modelo es
1.0


In [537]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
1.0
Exactitud del modelo
0.48295454545454547
la sensibilidad del modelo es
0.4262295081967213


### Submuestreo

In [538]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)
algoritmo_over_sampling = LogisticRegression()
algoritmo_over_sampling.fit(X_resampled, y_resampled)
y_pred_over_sampling = algoritmo_over_sampling.predict(X_test)
y_pred_over_sampling

array(['Nicolas', 'Nicolas', 'Nicolas', ..., 'otros usuarios', 'Nicolas',
       'Nicolas'], shape=(1760,), dtype=object)

In [539]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="Nicolas")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="Nicolas")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.16051660516605165
Exactitud del modelo
0.48295454545454547
la sensibilidad del modelo es
1.0


In [540]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
1.0
Exactitud del modelo
0.48295454545454547
la sensibilidad del modelo es
0.4262295081967213


## Rene

### Sin balanceo

In [541]:
df_no_numerico4["Usuario"]= df_no_numerico4["Usuario"].replace([27], "Rene")
df_no_numerico4["Usuario"]= df_no_numerico4["Usuario"].replace([24,18,14,17,11,9,8,13,16,22,12,10,20,15,26,28,32,6,3,19,5,29,21,25,31,23,7,2,4,1,30], "otros usuarios")

In [542]:
Var_Indep = df[["Administrador", "Juego", "auto push"]]
Var_Dep= df_no_numerico4["Usuario"]
X = Var_Indep
y = Var_Dep

In [543]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.3, random_state=None)
escala= StandardScaler()
X_train = escala.fit_transform(X_train)
X_test = escala.transform(X_test)
from sklearn.linear_model import LogisticRegression
algoritmo= LogisticRegression()
algoritmo.fit(X_train, y_train)
y_pred = algoritmo.predict(X_test)
y_pred

array(['otros usuarios', 'otros usuarios', 'otros usuarios', ...,
       'otros usuarios', 'otros usuarios', 'otros usuarios'],
      shape=(1760,), dtype=object)

In [544]:
matriz = confusion_matrix(y_test, y_pred)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[   0   15]
 [   0 1745]]


In [545]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="Rene")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="Rene")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.0
Exactitud del modelo
0.9914772727272727
la sensibilidad del modelo es
0.0


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [546]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.9914772727272727
Exactitud del modelo
0.9914772727272727
la sensibilidad del modelo es
1.0


### Reponderacion de clases

In [547]:
algoritmo_pond = LogisticRegression(class_weight="balanced")
algoritmo_pond.fit(X_train, y_train)
y_pred_pond = algoritmo_pond.predict(X_test)
y_pred_pond

array(['otros usuarios', 'otros usuarios', 'otros usuarios', ..., 'Rene',
       'otros usuarios', 'Rene'], shape=(1760,), dtype=object)

In [548]:
from sklearn.metrics import confusion_matrix
matriz = confusion_matrix(y_test, y_pred_pond)
print("Matriz de confusión")
print(matriz)

Matriz de confusión
[[  15    0]
 [ 312 1433]]


In [549]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="Rene")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="Rene")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.045871559633027525
Exactitud del modelo
0.8227272727272728
la sensibilidad del modelo es
1.0


In [550]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_pond, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_pond)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_pond, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
1.0
Exactitud del modelo
0.8227272727272728
la sensibilidad del modelo es
0.8212034383954154


### Submuestreo

In [551]:
from imblearn.over_sampling import SMOTE
smote = SMOTE()
X_resampled, y_resampled = smote.fit_resample(X_train, y_train)
algoritmo_over_sampling = LogisticRegression()
algoritmo_over_sampling.fit(X_resampled, y_resampled)
y_pred_over_sampling = algoritmo_over_sampling.predict(X_test)
y_pred_over_sampling

array(['otros usuarios', 'otros usuarios', 'otros usuarios', ..., 'Rene',
       'otros usuarios', 'Rene'], shape=(1760,), dtype=object)

In [552]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="Rene")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="Rene")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
0.045871559633027525
Exactitud del modelo
0.8227272727272728
la sensibilidad del modelo es
1.0


In [553]:
from sklearn.metrics import precision_score
precision = precision_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros usuarios")
print("Precision del modelo")
print(precision)
from sklearn.metrics import accuracy_score
exactitud = accuracy_score(y_test, y_pred_over_sampling)
print("Exactitud del modelo")
print(exactitud)
from sklearn.metrics import recall_score
sensibilidad = recall_score(y_test, y_pred_over_sampling, average="binary", pos_label="otros usuarios")
print("la sensibilidad del modelo es")
print(sensibilidad)

Precision del modelo
1.0
Exactitud del modelo
0.8227272727272728
la sensibilidad del modelo es
0.8212034383954154
